# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            S05p's Blog
tagline:          'A Jekyll theme'
description:      '주니어 개발자<br>김강섭의 블로그'
baseurl:          '/'

author:
  name:           'S05p'
  url:            https://github.com/s05p

github:
  repo:           https://github.com/poole/hyde

collections:
  Quant_project:
    output: true
    permalink: _posts/quant_projects/:name/


plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'category.html'
    title: ':cat'
    permalink: '/category/:cat/'
    per_page: 5
