# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: S05p's Blog
tagline: 'A Jekyll theme'
description: '주니어 백엔드 개발자<br>김강섭의 블로그'
baseurl: '/'
url: 'https://s05p.github.io'

author:
  name: 'S05p'
  url: https://github.com/s05p

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

# Pagination 설정
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Include 설정
include:
  - _pages

# Build 설정
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md

# Kramdown 설정
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false